(() => {
  const $ = id => document.getElementById(id);
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fold = s => String(s ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const finite = v => v !== null && v !== undefined && v !== '' && Number.isFinite(Number(v));
  const fmt = (v,d=1) => finite(v) ? Number(v).toFixed(d) : '—';
  const pct = v => finite(v) ? `${(100*Number(v)).toFixed(1)}%` : '—';
  let H,F,hi={},fi={},all=[],filtered=[],players=[],page=0;
  const PAGE=100;
  async function gz(resp){if(!resp.ok)throw new Error(`${new URL(resp.url).pathname} returned ${resp.status}`);if(typeof DecompressionStream!=='function')throw new Error('Modern DecompressionStream support required');const s=new Blob([await resp.arrayBuffer()]).stream().pipeThrough(new DecompressionStream('gzip'));return JSON.parse(await new Response(s).text());}
  const hv=(r,k)=>r[hi[k]], fv=(r,k)=>r[fi[k]], name=id=>H.playerIndex?.[id]?.name||`Player ${id}`;
  function align(){
    for(const [id,games] of Object.entries(H.byPlayer||{})){
      const fr=F.byPlayer?.[id]||[]; if(fr.length!==games.length)throw new Error(`feature/game row mismatch ${id}`);
      for(let i=0;i<games.length;i++){
        const g=games[i],r=fr[i]; for(const [a,b] of [['season','season'],['seasonType','seasonType'],['gameDate','indexDate'],['gameId','gameId'],['team','team'],['opponent','opponent']])if(String(hv(g,a))!==String(fv(r,b)))throw new Error(`feature/game key mismatch ${id}/${i}/${a}`);
        const min=Number(hv(g,'minutes'))||0, mult=min>0?36/min:null;
        all.push({id,name:name(id),g,r,season:hv(g,'season'),phase:hv(g,'seasonType'),date:hv(g,'gameDate'),gameId:hv(g,'gameId'),team:hv(g,'team'),opp:hv(g,'opponent'),min,started:hv(g,'started'),pts:Number(hv(g,'pts'))||0,reb:Number(hv(g,'reb'))||0,ast:Number(hv(g,'ast'))||0,tov:Number(hv(g,'tov'))||0,pm:Number(hv(g,'plusMinus'))||0,pts36:mult?(Number(hv(g,'pts'))||0)*mult:null,reb36:mult?(Number(hv(g,'reb'))||0)*mult:null,ast36:mult?(Number(hv(g,'ast'))||0)*mult:null,tov36:mult?(Number(hv(g,'tov'))||0)*mult:null});
      }
    }
  }
  function controls(){return {w:Number($('eWindow').value)||10,minPrior:Math.max(1,Number($('ePriorGames').value)||1),delta:Number($('eDelta').value)||0,priorMax:$('ePriorMax').value===''?Infinity:Number($('ePriorMax').value),targetMin:Number($('eTargetMin').value)||0,targetMax:$('eTargetMax').value===''?Infinity:Number($('eTargetMax').value),q:fold($('ePlayer').value),season:$('eSeason').value,phase:$('ePhase').value,team:$('eTeam').value,started:$('eStarted').value,minEpisodes:Math.max(1,Number($('eMinEpisodes').value)||1)};}
  function episode(e,c){const pre=`w${c.w}_`,base=fv(e.r,`${pre}mpg`),n=fv(e.r,`${pre}games`);if(!finite(base)||!finite(n))return null;const x={...e,base:Number(base),prior:Number(n),delta:e.min-Number(base)};if(x.prior<c.minPrior||x.delta<c.delta||x.base>c.priorMax||x.min<c.targetMin||x.min>c.targetMax)return null;if(c.q&&!fold(x.name).includes(c.q)||c.season&&x.season!==c.season||c.phase&&x.phase!==c.phase||c.team&&x.team!==c.team)return null;if(c.started==='true'&&x.started!==true||c.started==='false'&&x.started!==false||c.started==='unknown'&&x.started!==null)return null;return x;}
  function aggregate(rows,c){const m=new Map();for(const e of rows){let a=m.get(e.id);if(!a){a={id:e.id,name:e.name,n:0,base:0,min:0,delta:0,totalMin:0,pts:0,reb:0,ast:0,tov:0,pm:0,known:0,starts:0,teams:new Set(),seasons:new Set()};m.set(e.id,a);}a.n++;a.base+=e.base;a.min+=e.min;a.delta+=e.delta;a.totalMin+=e.min;a.pts+=e.pts;a.reb+=e.reb;a.ast+=e.ast;a.tov+=e.tov;a.pm+=e.pm;if(typeof e.started==='boolean'){a.known++;if(e.started)a.starts++;}a.teams.add(e.team);a.seasons.add(e.season);}const out=[...m.values()].filter(a=>a.n>=c.minEpisodes);for(const a of out){a.basePg=a.base/a.n;a.minPg=a.min/a.n;a.deltaPg=a.delta/a.n;a.pmPg=a.pm/a.n;const z=a.totalMin?36/a.totalMin:null;a.pts36=z?a.pts*z:null;a.reb36=z?a.reb*z:null;a.ast36=z?a.ast*z:null;a.tov36=z?a.tov*z:null;a.startRate=a.known?a.starts/a.known:null;}return out.sort((a,b)=>b.n-a.n||b.deltaPg-a.deltaPg||a.name.localeCompare(b.name));}
  function apply(){const c=controls();filtered=all.map(e=>episode(e,c)).filter(Boolean);players=aggregate(filtered,c);page=0;summary();support();playerTable();episodeTable();}
  function summary(){const avg=k=>filtered.length?filtered.reduce((s,e)=>s+Number(e[k]||0),0)/filtered.length:null,known=filtered.filter(e=>typeof e.started==='boolean').length;const cards=[['Episodes',filtered.length.toLocaleString()],['Players',new Set(filtered.map(e=>e.id)).size.toLocaleString()],['Prior MPG',fmt(avg('base'))],['Target MIN',fmt(avg('min'))],['Avg Δ MIN',fmt(avg('delta'))],['Starter known',filtered.length?`${(100*known/filtered.length).toFixed(1)}%`:'—']];$('eSummary').innerHTML=cards.map(([k,v])=>`<div class="ev-card"><div class="k">${esc(k)}</div><div class="v">${esc(v)}</div></div>`).join('');}
  const bb=[['<12',-Infinity,12],['12–16',12,16],['16–20',16,20],['20–24',20,24],['24–28',24,28],['28+',28,Infinity]],tb=[['<20',-Infinity,20],['20–24',20,24],['24–28',24,28],['28–32',28,32],['32+',32,Infinity]];
  function support(){let s='<div class="hdr">Prior ↓ / Target →</div>'+tb.map(x=>`<div class="hdr">${x[0]}</div>`).join('');for(const b of bb){s+=`<div class="hdr">${b[0]}</div>`;for(const t of tb){const n=filtered.filter(e=>e.base>=b[1]&&e.base<b[2]&&e.min>=t[1]&&e.min<t[2]).length;s+=`<div><span class="count ${n<20?'low':''}">${n.toLocaleString()}</span></div>`;}}$('eSupport').innerHTML=s;}
  function playerTable(){const b=$('ePlayerTable').querySelector('tbody');b.innerHTML=players.length?players.slice(0,250).map(a=>`<tr><td><span class="ev-player">${esc(a.name)}</span><span class="ev-sub">${esc([...a.teams].sort().join('/'))} · ${esc([...a.seasons].sort().join(', '))}</span></td><td>${a.n}</td><td>${fmt(a.basePg)}</td><td>${fmt(a.minPg)}</td><td>${fmt(a.deltaPg)}</td><td>${fmt(a.pts36)}</td><td>${fmt(a.reb36)}</td><td>${fmt(a.ast36)}</td><td>${fmt(a.tov36)}</td><td>${fmt(a.pmPg)}</td><td>${pct(a.startRate)}</td></tr>`).join(''):'<tr><td colspan="11">No players match this evidence slice.</td></tr>';}
  function episodeTable(){const s=[...filtered].sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(b.gameId).localeCompare(String(a.gameId))),pages=Math.max(1,Math.ceil(s.length/PAGE));page=Math.min(page,pages-1);const chunk=s.slice(page*PAGE,(page+1)*PAGE),b=$('eEpisodeTable').querySelector('tbody');b.innerHTML=chunk.length?chunk.map(e=>`<tr><td><span class="ev-player">${esc(e.name)}</span></td><td>${esc(e.date)}</td><td>${esc(e.season)}</td><td>${esc(e.team)}</td><td>${esc(e.opp)}</td><td>${fmt(e.base)}</td><td>${fmt(e.min)}</td><td>${fmt(e.delta)}</td><td>${e.started===true?'Yes':e.started===false?'No':'—'}</td><td>${e.pts}</td><td>${e.reb}</td><td>${e.ast}</td><td>${e.tov}</td><td>${e.pm}</td></tr>`).join(''):'<tr><td colspan="14">No episodes match this slice.</td></tr>';$('ePage').textContent=s.length?`Page ${page+1} of ${pages} · ${s.length.toLocaleString()} episodes`:'0 episodes';$('ePrev').disabled=page<=0;$('eNext').disabled=page>=pages-1;}
  const cell=v=>{const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;};function dl(name,rows){const b=new Blob([rows.map(r=>r.map(cell).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();URL.revokeObjectURL(a.href);}
  function exportPlayers(){const r=[['Player','Player ID','Episodes','Prior MPG','Target MIN','Delta MIN','PTS36','REB36','AST36','TOV36','PlusMinus/Game','Known Starts','Known Starter Games','Start Rate','Teams','Seasons']];for(const a of players)r.push([a.name,a.id,a.n,a.basePg,a.minPg,a.deltaPg,a.pts36,a.reb36,a.ast36,a.tov36,a.pmPg,a.starts,a.known,a.startRate,[...a.teams].sort().join('|'),[...a.seasons].sort().join('|')]);dl('tulip-role-expansion-player-evidence.csv',r);}
  function exportEpisodes(){const r=[['Player','Player ID','Date','Season','Phase','Game ID','Team','Opponent','Prior MPG','Prior Games','Target MIN','Delta MIN','Started','PTS','REB','AST','TOV','PlusMinus']];for(const e of filtered)r.push([e.name,e.id,e.date,e.season,e.phase,e.gameId,e.team,e.opp,e.base,e.prior,e.min,e.delta,e.started??'',e.pts,e.reb,e.ast,e.tov,e.pm]);dl('tulip-role-expansion-episodes.csv',r);}
  function reset(){$('eWindow').value='10';$('ePriorGames').value='5';$('eDelta').value='6';$('ePriorMax').value='';$('eTargetMin').value='20';$('eTargetMax').value='48';for(const id of ['ePlayer','eSeason','ePhase','eTeam','eStarted'])$(id).value='';$('eMinEpisodes').value='1';apply();}
  function bind(){for(const id of ['eWindow','ePriorGames','eDelta','ePriorMax','eTargetMin','eTargetMax','ePlayer','eSeason','ePhase','eTeam','eStarted','eMinEpisodes'])$(id).addEventListener(id==='ePlayer'?'input':'change',apply);$('eReset').onclick=reset;$('eExportPlayers').onclick=exportPlayers;$('eExportEpisodes').onclick=exportEpisodes;$('ePrev').onclick=()=>{if(page>0){page--;episodeTable();}};$('eNext').onclick=()=>{page++;episodeTable();};}
  async function load(){$('eStatus').textContent='Loading game and strictly-past role feature products…';[H,F]=await Promise.all([fetch('./public/history-games.json.gz',{cache:'no-store'}).then(gz),fetch('./public/history-role-features.json.gz',{cache:'no-store'}).then(gz)]);if(H.schemaVersion!==1||F.schemaVersion!==1)throw new Error('Unsupported evidence product schema');if(!/strictly earlier/i.test(F.featureTiming||''))throw new Error('Role feature timing contract is not strictly-past');if(F.sourceHistoryGeneratedAt!==H.generatedAt)throw new Error('Role features do not bind to this game product');hi=Object.fromEntries(H.rowSchema.map((k,i)=>[k,i]));fi=Object.fromEntries(F.rowSchema.map((k,i)=>[k,i]));align();$('eSeason').innerHTML='<option value="">All seasons</option>'+(H.seasons||[]).map(s=>`<option>${esc(s)}</option>`).join('');const teams=[...new Set(all.map(e=>e.team).filter(Boolean))].sort();$('eTeam').innerHTML='<option value="">All teams</option>'+teams.map(t=>`<option>${esc(t)}</option>`).join('');bind();apply();$('eStatus').textContent=`${all.length.toLocaleString()} aligned historical index games · features use strictly earlier dates only`;}
  window.__evidenceLab={get total(){return all.length},get episodes(){return filtered.length},get players(){return players.length},apply};load().catch(e=>{console.error(e);$('eStatus').textContent=`Evidence Lab failed to load: ${e.message}`;});
})();
