import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {parseIndividualBio,validBirthdate,fetchIndividualBio,refreshIndividualBioCache,individualBioPeople} from '../scripts/lib/individual-bios.mjs';
const headers=['PERSON_ID','HEIGHT','WEIGHT','BIRTHDATE','POSITION'];
const body=(id=1,date='2000-02-29T00:00:00')=>({resultSets:[{name:'CommonPlayerInfo',headers,rowSet:[[id,'6-6','210',date,'Forward']]}]});
const bio=parseIndividualBio(body(),1);
assert.equal(bio.birthdate,'2000-02-29T00:00:00');
for(const bad of [null,{},body(2),body(true),body(1,'2001-02-29'),{resultSets:[{name:'CommonPlayerInfo',headers,rowSet:[]}]},{resultSets:[{name:'CommonPlayerInfo',headers,rowSet:[[1]]}]}])assert.throws(()=>parseIndividualBio(bad,1));
for(const bad of ['',false,0,'2000-13-01','2000-02-30','2000-01-01Tgarbage','2099-01-01'])assert.equal(validBirthdate(bad),false);
const urls=[];
const fallback=await fetchIndividualBio(1,{wait:async()=>{},fetchImpl:async url=>{urls.push(url);return {ok:true,json:async()=>urls.length===1?{}:body()};}});
assert.equal(fallback.height,'6-6');assert.equal(urls.length,2);assert.match(urls[1],/LeagueID=20/);
await assert.rejects(fetchIndividualBio(1,{wait:async()=>{},fetchImpl:async()=>({ok:true,json:async()=>body(2)})}),/identity/);
const root=fs.mkdtempSync(path.join(os.tmpdir(),'bio-refresh-'));
try {
  const file=path.join(root,'birthdates.json');
  const before=JSON.stringify({1:{name:'Known',birthdate:bio.birthdate},2:{name:'Old failed placeholder',birthdate:null}});
  fs.writeFileSync(file,before);
  const people=new Map([[1,'Known'],[2,'Retryable'],[3,'New rookie']]),calls=[];
  const opts={file,people,birthdatesOnly:true,wait:async()=>{},report:()=>{}};
  const failed=await refreshIndividualBioCache({...opts,fetchBio:async id=>{calls.push(id);throw Error('offline');}});
  assert.deepEqual(calls,[2,2,2,3,3,3]);assert.equal(failed.failed,2);
  assert.equal(fs.readFileSync(file,'utf8'),before,'all failed lookups must preserve exact cached bytes');
  const success=await refreshIndividualBioCache({...opts,fetchBio:async()=>bio});
  assert.equal(success.fetched,2);assert.equal(JSON.parse(fs.readFileSync(file))[3].birthdate,bio.birthdate);
  const partial=path.join(root,'partial.json');fs.writeFileSync(partial,JSON.stringify({1:{name:'Known height',height:'6-6',weight:null,birthdate:null}}));
  await refreshIndividualBioCache({file:partial,people:new Map([[1,'Known height']]),wait:async()=>{},fetchBio:async()=>({...bio,height:null}),report:()=>{}});
  const preserved=JSON.parse(fs.readFileSync(partial))[1];assert.equal(preserved.height,'6-6');assert.equal(preserved.weight,'210');
  fs.writeFileSync(partial,'not json');await assert.rejects(refreshIndividualBioCache({...opts,file:partial}),/JSON/);assert.equal(fs.readFileSync(partial,'utf8'),'not json');
  fs.mkdirSync(path.join(root,'public'));fs.mkdirSync(path.join(root,'scripts/data/live'),{recursive:true});
  fs.writeFileSync(path.join(root,'public/data.json'),JSON.stringify({leagues:{NBA:[{nbaPersonId:1,name:'Existing',height:'6-6',weight:210},{nbaPersonId:null,name:'No official ID'}],GLEAGUE:[]}}));
  const columns=['PERSON_ID','PLAYER_FIRST_NAME','PLAYER_LAST_NAME','TEAM_ID','TEAM_ABBREVIATION','POSITION','HEIGHT','WEIGHT','COUNTRY','DRAFT_YEAR','DRAFT_ROUND','DRAFT_NUMBER','ROSTER_STATUS','FROM_YEAR','TO_YEAR'];
  const rows=Array.from({length:400},(_,i)=>[i+2,'New','Player '+i,1610612737,'ATL','G',null,null,'USA',2026,1,1,1,2026,2026]);
  fs.writeFileSync(path.join(root,'scripts/data/live/roster.json'),JSON.stringify({source:'stats.nba.com/stats/playerindex',season:'2026-27',fetchedAt:'2026-10-01T00:00:00Z',headers:columns,rows}));
  const all=individualBioPeople(root);assert.equal(all.size,401);assert.equal(all.has(null),false);assert.equal(all.get(2),'New Player 0');
  const missing=individualBioPeople(root,{missingSizeOnly:true});assert.equal(missing.size,400);assert.equal(missing.has(1),false);
} finally {fs.rmSync(root,{recursive:true,force:true});}
console.log('Individual bio refresh passed: exact identity/schema/calendar, G League fallback, retryable nulls, failed-cache preservation, no blank downgrades and newly rostered rookie coverage');
